<a href="https://colab.research.google.com/github/MarkG/Pytorch-Tutorial-Youtube/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import numpy as np

In [13]:
#shape
np1 = np.array([[1,2,3,4,5]])
print(np1.shape)
#range
np2 = np.arange(2, 10, 2)
# zeros
print (np2)
np4 = np.zeros(10)
# multi-dimentional zeros
np5 = np.zeros((2,3))
print (np5)
# Full
np6 = np.full((2,3), 8)
print (np6)
# convert list to np
my_list1 = [1,2,3]
np7 = np.array(my_list1)
print (np7)

(1, 5)
[2 4 6 8]
[[0. 0. 0.]
 [0. 0. 0.]]
[[8 8 8]
 [8 8 8]]


In [37]:
# slicing np arrays
np1 = np.array([1,2,3,4,5,6,7,8,9])

# return 2-5
print(np1[1:5])

# return from 4 till the end
print (np1[3:])

# return negative  slicing
print (np1[-3:-1])

#steps
print(np1[1:5]) # 2-5
print(np1[1:5:2]) # 2-5 in step of 2
print(np1[::2]) # step entire array of 2

#step a 2d array
np2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(np2[1,2]) # pull out single item - 7
print(np2[0:1,1:3]) # slice 2-d array 2,3
print(np2[0:2,1:3]) # slice 2-d array from both rows 2,3 and 7,8

[2 3 4 5]
[4 5 6 7 8 9]
[7 8]
[2 3 4 5]
[2 4]
[1 3 5 7 9]
8
[[2 3]]
[[2 3]
 [7 8]]


In [42]:
# Numpy universal functions
np1 = np.array([-3,-2,-1,0,1,2,3,4,5,6,7,8,9])
print(np1)

# Square route of each element
print(np.sqrt(np1))

# Absolute value
print(np.abs(np1))

# Exponential
print(np.exp(np1))

# Min/Max
print(np.min(np1))
print(np.max(np1))

# Mean
print(np.mean(np1))
# Log
print(np.log(np1))
print(np.log10(np1))

# Sign positive or negative
print(np.sign(np1))

# Trig - sin cos
print(np.sin(np1))
print(np.cos(np1))

https://numpy.org/devdocs/reference/ufuncs.html

[-3 -2 -1  0  1  2  3  4  5  6  7  8  9]
[-0.14112001 -0.90929743 -0.84147098  0.          0.84147098  0.90929743
  0.14112001 -0.7568025  -0.95892427 -0.2794155   0.6569866   0.98935825
  0.41211849]
[-0.9899925  -0.41614684  0.54030231  1.          0.54030231 -0.41614684
 -0.9899925  -0.65364362  0.28366219  0.96017029  0.75390225 -0.14550003
 -0.91113026]


In [46]:
# Copy vs View
np1 = np.array([1,2,3,4,5,6,7,8,9])

#create a view
np2 = np1.view()
print(f'Original np1: {np1}')
print(f'Original np2: {np2}')
np1[0] = 10
print(f'Modified np1: {np1}')
print(f'Original np2: {np2}')

#create a copy
np2 = np1.copy()
print(f'Original np1: {np1}')
print(f'Original np2: {np2}')
np1[0] = 10
print(f'Modified np1: {np1}')
print(f'Original np2: {np2}')



Original np1: [1 2 3 4 5 6 7 8 9]
Original np2: [1 2 3 4 5 6 7 8 9]
Modified np1: [10  2  3  4  5  6  7  8  9]
Original np2: [10  2  3  4  5  6  7  8  9]


In [52]:
# Shape and reshape

# Create 1-D mp array and get shape
np1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(np1.shape)

# Create 2-D mp array and get shape
np2 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(np2.shape)

# Reshape 2-D
np3 = np1.reshape(3,4)
print(np3.shape, np3)

# Reshape 3-D
np4 = np1.reshape(2,3,2)
print(np4.shape, np4)

#Flatten to 1-D
np5 = np4.reshape(-1)
print(np5.shape, np5)

(3, 4) [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(2, 3, 2) [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(12,) [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [57]:
# iterate thru np array
# # 1-d
# np1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
# for x in np1:
#     print(x)

# # 2-d
# np2 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
# for x in np2:
#     print(x) # print rows
#     for y in x:
#         print(y) # print individual items

# # 3-d
# np3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
# for x in np3:
#     print(x) # print matrix
#     for y in x:
#         print(y) # print rows
#         for z in y:
#             print(z) # print individual items

# Use np.nditer()
np1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
for x in np.nditer(np1):
    print(x) # print individual items
np3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for x in np.nditer(np3):
    print(x) # print individual items

1
2
3
4
5
6
7
8
9
10
11
12
1
2
3
4
5
6
7
8
9


In [68]:
# sorting np arrays (dosn't change the original)

# np1 = np.array([1,2,3,4,5,6])[::-1]
# print(np1, np.sort(np1), np1)

# # alphabetical
# np2 = np.array(['banana', 'cherry', 'apple'])
# print(np2, np.sort(np2))

# # boolean
# np3 = np.array([True, False, True])
# print(np3, np.sort(np3))

# 2-d
np4 = np.array([[3,2,4],[5,0,1]])
print(np4, '\n', np.sort(np4))

[[3 2 4]
 [5 0 1]] 
 [[2 3 4]
 [0 1 5]]


In [73]:
# searching np array
np1 = np.array([1,2,3,4,5,6,7,8,9,10,3])

x = np.where(np1 == 3) # resturns the position tuple of 3
print(x, x[0])

x = np.where(np1 % 2 == 0) # resturns the position tupless of all even numbers
print(x, x[0])

x = np.where(np1 % 2 == 1) # resturns the position tupless of all odd numbers
print(x, x[0])

(array([ 2, 10]),) [ 2 10]
(array([1, 3, 5, 7, 9]),) [1 3 5 7 9]
(array([ 0,  2,  4,  6,  8, 10]),) [ 0  2  4  6  8 10]


In [76]:
# Filtering np arrays with Boolean Index Lists
np1 = np.array([1,2,3,4,5,6,7,8,9,10])

# x = [True, True, False, False, False, False, False, False, False, False]
# print(np1[x])

# # Create a filter array
# filtered = []
# for element in np1:
#     if element % 2 == 0:
#         filtered.append(True)
#     else:
#         filtered.append(False)
# print(np1[filtered])

# Shortcut
filtered = np1 % 2 == 0
print(filtered, '\n', np1[filtered])

[False  True False  True False  True False  True False  True] 
 [ 2  4  6  8 10]
